export const TextValue = {
    //Sections
    Home: "Inicio",
    ItemCheck: "Revision de Articulo",
    GoodsReceipt: "Entrada",
    GoodsReceiptSupervisor: "Supervisor de Entrada",
    GoodsReceiptReport: "Reporte de Entradas",
    GoodsReceiptVSExit: "Reporte de Entradas vs Salida",

    //Buttons / Status
    No: "No",
    Yes: "Sí",
    Add: "Agregar",
    Approve: "Aprobar",
    Cancel: "Cancelar",
    Delete: "Eliminar",
    Select: "Seleccione",
    Update: "Actualizar",
    Finish: "Finalizar",
    Create: "Crear",
    Accept: "Aceptar",
    QRCode: "Código QR",
    ID: "Identificación",
    Code: "Código",
    Description: "Descripcion",
    Barcode: "Código de Barra",
    Barcodes: "Códigos de Barra",
    Unknown: "Desconocido",
    Clear: "Borrar",
    Approved: "El documento ha sido finalizado con éxito.",
    Cancelled: "El documento ha sido cancelado con éxito.",

    //Statues
    OpenStatus: "Abierto",
    InProgressStatus: "En Proceso",
    FinishedStatus: "Finalizado",
    CancelledStatus: "Cancelado",
    ProcessingStatus: "Procesando",

    //Fields
    Item: "Articulo",
    Vendor: "Proveedor",
    Number: "Número",
    DocDate: "Fecha",
    CreatedBy: "Creado Por",
    Status: "Estado",
    Box: "Caja",
    Boxes: "Cajas",
    Of: "de",
    Date: "Fecha",
    Transaction: "Transacción",
    Filters: "Filtros",
    Execute: "Ejecutar",
    TransferRequest: "Solicitud de Transferencia",
    PurchaseOrder: "Orden de Compra",
    SalesOrder: "Orden de Venta",
    ReservedInvoice: "Factura Reservada",
    DocumentNumber: "Numero de Documento",
    Address: "Direccion",
    Customer: "Cliente",
    OpenQuantity: "Cantidad Abierta",
    Quantity: "Cantidad",
    Message: 'Mensaje',
    Messages: 'Mensajes',
    Time: 'Tiempo',
    Delivery: "Entrega",
    Showroom: "Showroom",
    InWarehouse: "En Bodega",
    Stock: "Inventario",
    Comment: 'Comentario',
    SupervisorCode: 'Codigo de Supervisor',
    Reason: "Razon",
    NumInBuy: 'Cantidad en Unidad',
    Automatic: 'Automatico',
    SpecificDocuments: 'Documentos Especificos',
    DocumentsList: 'Lista de Documentos',

    //Field Description
    SelectVendor: "Seleccione el Proveedor",
    SelectBox: "Seleccione la Caja",

    //Validations
    GoodsReceiptNotFound: "La entrada #{0} no es válida",
    GoodsReceiptStatusError: "El estado de la entrada #{0} es {1}.\nNo se puede continuar.",
    GoodsReceiptIsClosed: "Entrada #{0} esta cerrada",
    IDRequired: "Debe introducir una identificación",
    VendorRequired: "Debe seleccionar el proveedor",
    DocumentRequired: "Debe introducir el numero de documento",
    DuplicateNotAllowed: 'Duplicate values are not allowed.',
    InvalidID: "Identificación Inválida",
    ScanCodeRequired: "Debe escanear un código",
    BarcodeRequired: "Debe escanear un código de barra",
    BarcodeOrItemRequired: "Debe escanear un código de barra or articulo",
    BarcodeNotFound: 'No se encontro el codigo de barra "{0}"',
    MultipleItemsError: "Codigo retorno multiples codigos de articulos:\n{0}.\nSolicite la correcion en el sistema e intente de nuevo.",
    NoExitData: "No tiene salidas o transferencias pendientes.",
    InvalidScanCode: "Código Erróneo",
    ScanConfirmStoreInWarehouse: "Guardar en Bodega",
    ScanConfirmFulfillment: "Separar para Entrega a Cliente",
    ScanConfirmShowroom: "Enviar a Showroom",
    ScanConfirmSupervisor: "Separar para Supervisor",
    ScanConfirmBoxNumber: "Confirmar numero de caja",
    UpdateLineStatusError: "Transaccion {0} no esta en proceso",
    UpdateLineLineStatusError: "Transaccion {0}, Linea {1} no esta en abierta",
    UpdateLineReason: "Estado de cancelacion invalido",
    UpdateLineWrongSupervisorPassword: "Contraseña de supervision erroneo",
    UpdateLineNotSupervisorError: "El codigo introducido no es de un supervisor",
    NoDataFound: "No se encontro datos",
    MultipleItemsDetected: "Multiples Articulos Detectados",
    UnknownError: 'Unknown error',
    BadDocumentError: 'La {0} #{1} {2}',
    DoesNotExists: 'no existe',
    IsNotOpen: 'no esta abierta',

    //Dialog
    ConfirmAction: "Confirmar Acción",
    ConfirmApproveDocument: "¿Está seguro que desea aprobar el documento #{0}?",
    ConfirmCancelDocument: "¿Está seguro que desea cancelar el documento #{0}?",
    ConfirmFinishDocument: "¿Está seguro que desea finalizar el documento #{0}?",
    ActionCannotReverse: "Esta acción no se puede revertir",
    ConfirmItemBarCode: "¿Esta seguro que el codigo {1} le pertenece al articulo {0}?",

}
